
import { Tag } from "./types";

// ダミータグデータ（必要に応じて拡充）
export const TAGS: Tag[] = [
  {
    id: "T001",
    name: "オンメタルUHFハードタグS",
    band: "UHF",
    on_metal: true,
    mounting_methods: ["粘着","リベット/ネジ"],
    size_mm: [35,10,3],
    curved_surface: false,
    read_range_m: [0.5,6],
    temp: [-20,85],
    ip: "IP67",
    unit_cost_tier: "mid",
    printable: false, encodeable: true,
    notes: "小型資産管理向け。屋外可。",
  },
  {
    id: "T002",
    name: "UHFラベル（汎用）",
    band: "UHF",
    on_metal: false,
    mounting_methods: ["粘着"],
    size_mm: [95,12,0.2],
    curved_surface: true,
    read_range_m: [1,10],
    temp: [0,60],
    unit_cost_tier: "low",
    printable: true, encodeable: true,
    notes: "段ボール・プラ容器向け。大量一括読取。",
  },
  {
    id: "T003",
    name: "洗濯タグ（縫付）",
    band: "UHF",
    on_metal: false,
    mounting_methods: ["縫い付け"],
    size_mm: [60,15,1.6],
    curved_surface: true,
    read_range_m: [0.5,4],
    temp: [-20,120],
    wash_cycles: 200,
    ip: "IP68",
    unit_cost_tier: "mid",
    printable: false, encodeable: true,
    notes: "リネン・ユニフォーム向け。洗濯/乾燥耐性。",
  },
  {
    id: "T004",
    name: "ケーブルタイタグ",
    band: "UHF",
    on_metal: false,
    mounting_methods: ["ケーブルタイ","吊り下げ"],
    size_mm: [30,25,3],
    curved_surface: true,
    read_range_m: [1,6],
    temp: [-20,85],
    ip: "IP54",
    unit_cost_tier: "mid",
    printable: false, encodeable: true,
    notes: "通い箱/パレットの反復利用に。",
  },
  {
    id: "T005",
    name: "NFCステッカー（HF）",
    band: "HF/NFC",
    on_metal: false,
    mounting_methods: ["粘着"],
    size_mm: [30,30,0.2],
    curved_surface: true,
    read_range_m: [0,0.05],
    temp: [-10,60],
    unit_cost_tier: "low",
    printable: true, encodeable: true,
    notes: "スマホタッチ用途。近接読み取り。",
  },
];
